### PR TITLE
fix: Icon component cause error in remix

### LINKED ISSUE #687: Icon component cause error in remix
When using a Custom created Icon in a Remix App

Eg: 
```js
import Icon from "@ant-design/icons";

const HeartSvg = () => (
  <svg width="1em" height="1em" fill="currentColor" viewBox="0 0 1024 1024">
    <title>heart icon</title>
    <path d="M923 283.6c-13.4-31.1-32.6-58.9-56.9-82.8-24.3-23.8-52.5-42.4-84-55.5-32.5-13.5-66.9-20.3-102.4-20.3-49.3 0-97.4 13.5-139.2 39-10 6.1-19.5 12.8-28.5 20.1-9-7.3-18.5-14-28.5-20.1-41.8-25.5-89.9-39-139.2-39-35.5 0-69.9 6.8-102.4 20.3-31.4 13-59.7 31.7-84 55.5-24.4 23.9-43.5 51.7-56.9 82.8-13.9 32.3-21 66.6-21 101.9 0 33.3 6.8 68 20.3 103.3 11.3 29.5 27.5 60.1 48.2 91 32.8 48.9 77.9 99.9 133.9 151.6 92.8 85.7 184.7 144.9 188.6 147.3l23.7 15.2c10.5 6.7 24 6.7 34.5 0l23.7-15.2c3.9-2.5 95.7-61.6 188.6-147.3 56-51.7 101.1-102.7 133.9-151.6 20.7-30.9 37-61.5 48.2-91 13.5-35.3 20.3-70 20.3-103.3 0.1-35.3-7-69.6-20.9-101.9z" />
  </svg>
);

const HeartIcon = (props) => (
  <Icon component={HeartSvg} {...props} />
);

export default function Index() {
  return (
    <div>
      <HeartIcon />
    </div>
  )
}
```

It causes the following error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

dependencies:
"@ant-design/icons": "^5.6.1",
"@remix-run/react": "^2.16.0",
"react": "^18.2.0",

### PR DESCRIPTION
**Pull request by andypho**
fix https://github.com/ant-design/ant-design-icons/issues/687

### CODE REVIEW

**Comment by seanparmelee** [comment]
Hi @andypho, thanks for opening up a PR to fix this issue!

It looks like this one is for 6.x, any chance you have a fix for 5.x? I tried back-porting this one, but I'm still running into the same issue. Or maybe we're experiencing different issues 🤔

**Comment by andypho** [comment]
> Hi @andypho, thanks for opening up a PR to fix this issue!
> 
> It looks like this one is for 6.x, any chance you have a fix for 5.x? I tried back-porting this one, but I'm still running into the same issue. Or maybe we're experiencing different issues 🤔

I did this pull request when I was using version `5.6.1`.

File: packages/icons-react/src/utils.ts [hunk 1]
```diff
@@ -12,7 +12,9 @@ function camelCase(input: string) {
 }
 
 export function warning(valid: boolean, message: string) {
-  warn(valid, `[@ant-design/icons] ${message}`);
+  if (typeof warn === 'function') {
+    warn(valid, `[@ant-design/icons] ${message}`);
+  }
```
Comment (afc163) [inline packages/icons-react/src/utils.ts]: Why is warn undefined here? Is there an issue with the implementation of @rc-component/util/lib/warning?

Comment (seanparmelee) [reply packages/icons-react/src/utils.ts]: it wasn't `undefined` in my testing, it seems the issue is how the library is exporting for CJS: https://github.com/ant-design/ant-design-icons/issues/687#issuecomment-3273209972

Comment (andypho) [reply packages/icons-react/src/utils.ts]: I think it has something to do with the way it import in the server side.
if I change to the following, no error as well:

```
import { warningOnce } from "@rc-component/util/lib/warning";

export function warning(valid: boolean, message: string) {
  warningOnce(valid, `[@ant-design/icons] ${message}`);
 }
```

**Comment by seanparmelee** [comment]
> > Hi @andypho, thanks for opening up a PR to fix this issue!
> > It looks like this one is for 6.x, any chance you have a fix for 5.x? I tried back-porting this one, but I'm still running into the same issue. Or maybe we're experiencing different issues 🤔
> 
> I did this pull request when I was using version `5.6.1`.

My apologies, I see that the error in the issue you logged is

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
whereas mine is

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

... so we are seeing separate issues (`undefined` vs `object`).
